from __future__ import annotations

from pathlib import Path

from yolo_compare.config import ExperimentConfig, read_yaml, write_yaml
from yolo_compare.version_adapters.base import runtime_python
from yolo_compare.version_adapters.legacy_repo import LegacyRepoAdapter


class YoloV6Adapter(LegacyRepoAdapter):
    train_script = "tools/train.py"
    test_script = "tools/eval.py"
    detect_script = "tools/infer.py"

    def default_weights_path(self, run_dir: Path) -> Path:
        train_best = run_dir / "train" / "weights" / "best_ckpt.pt"
        if train_best.exists() or not (run_dir / "weights" / "best_ckpt.pt").exists():
            return train_best
        return run_dir / "weights" / "best_ckpt.pt"

    def train_command(
        self,
        repo_dir: Path,
        experiment: ExperimentConfig,
        prepared_data_yaml: Path,
        run_dir: Path,
    ) -> list[str]:
        train = experiment.train
        config_file = self.training_config_file(repo_dir, run_dir)
        data_yaml = self.compatible_data_yaml(experiment, prepared_data_yaml, run_dir)
        return [
            *runtime_python(self.model),
            str(repo_dir / self.train_script),
            "--img-size",
            str(train.imgsz),
            "--batch-size",
            str(train.batch),
            "--epochs",
            str(train.epochs),
            "--data-path",
            str(data_yaml),
            "--conf-file",
            str(config_file),
            "--output-dir",
            str(run_dir),
            "--name",
            "train",
            "--workers",
            str(train.workers),
        ]

    def training_config_file(self, repo_dir: Path, run_dir: Path) -> Path:
        config_file = self.model.config_file or "configs/yolov6n.py"
        source = repo_dir / config_file
        weights = Path(self.model.weights)
        if weights.is_absolute() or not self.model.raw.get("weights_url") or not source.exists():
            return source

        target = run_dir / "snapshots" / f"{Path(config_file).stem}.pretrained.py"
        pretrained = (repo_dir / weights).resolve()
        content = source.read_text(encoding="utf-8")
        content += (
            "\n\n# Generated by yolo_compare to fine-tune from the configured official weights.\n"
            f"model['pretrained'] = {str(pretrained)!r}\n"
        )
        target.write_text(content, encoding="utf-8")
        return target

    def eval_command(
        self,
        repo_dir: Path,
        experiment: ExperimentConfig,
        prepared_data_yaml: Path,
        run_dir: Path,
        weights_path: Path,
    ) -> list[str]:
        train = experiment.train
        data_yaml = self.compatible_data_yaml(experiment, prepared_data_yaml, run_dir)
        return [
            *runtime_python(self.model),
            str(repo_dir / self.test_script),
            "--data",
            str(data_yaml),
            "--weights",
            str(weights_path),
            "--batch-size",
            str(train.batch),
            "--img-size",
            str(train.imgsz),
            "--task",
            experiment.test.split,
            "--save_dir",
            str(run_dir / experiment.test.split),
        ]

    def detect_command(
        self,
        repo_dir: Path,
        experiment: ExperimentConfig,
        run_dir: Path,
        weights_path: Path,
    ) -> list[str]:
        train = experiment.train
        test = experiment.test
        data_yaml = self.compatible_data_yaml(
            experiment,
            run_dir / "snapshots" / "data.fixed.yaml",
            run_dir,
        )
        source = self.compatible_image_dir(experiment, run_dir, test.split)
        return [
            *runtime_python(self.model),
            str(repo_dir / self.detect_script),
            "--weights",
            str(weights_path),
            "--source",
            str(source),
            "--yaml",
            str(data_yaml),
            "--img-size",
            str(train.imgsz),
            "--conf-thres",
            str(test.conf),
            "--iou-thres",
            str(test.iou),
            "--save-dir",
            str(run_dir / "predict" / test.split),
        ]

    def compatible_data_yaml(
        self,
        experiment: ExperimentConfig,
        prepared_data_yaml: Path,
        run_dir: Path,
    ) -> Path:
        compat_root = run_dir / "snapshots" / "yolov6_data"
        for split in ("train", "valid", "test"):
            compat_images = compat_root / "images" / split
            compat_labels = compat_root / "labels" / split
            ensure_symlink(experiment.dataset.root / split / "images", compat_images)
            ensure_symlink(experiment.dataset.root / split / "labels", compat_labels)

        data = read_yaml(prepared_data_yaml)
        data["train"] = str(compat_root / "images" / "train")
        data["val"] = str(compat_root / "images" / "valid")
        data["test"] = str(compat_root / "images" / "test")
        output = run_dir / "snapshots" / "data.yolov6.yaml"
        write_yaml(output, data)
        return output

    def compatible_image_dir(
        self,
        experiment: ExperimentConfig,
        run_dir: Path,
        split: str,
    ) -> Path:
        split_dir = "valid" if split == "val" else split
        return run_dir / "snapshots" / "yolov6_data" / "images" / split_dir


def ensure_symlink(target: Path, link: Path) -> None:
    if link.exists() or link.is_symlink():
        return
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(target.resolve(), target_is_directory=True)
